version: '3'

services:

  web:
    build: 
      context: .
      dockerfile: ${PWD}/nginx/Dockerfile
    restart: always  
    volumes:
      - ${PWD}/data/website:/usr/share/nginx/html
      - ${PWD}/data/nginx/nginx_logs:/var/log/nginx:rw
      - ${PWD}/data/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ${PWD}/data/nginx/conf.d:/etc/nginx/conf.d:rw
      - ${PWD}/../letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"

networks:
  default:
    external:
      name: nginx-network


